services:
  - type: web
    name: rogen
    env: static
    buildCommand: |
      # Install Flutter
      git clone https://github.com/flutter/flutter.git -b stable --depth 1
      export PATH="$PATH:$PWD/flutter/bin"
      flutter doctor -v
      flutter config --enable-web
      flutter pub get
      flutter build web --release
    staticPublishPath: build/web
    envVars:
      - key: FLUTTER_VERSION
        value: 3.16.0
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
